### ISSUE TITLE
刷新数据时，重新调用init报错

### ISSUE THREAD

**Issue by HuangShun** [KunMinX/Linkage-RecyclerView#50]
`    Process: com.kunminx.linkagelistview, PID: 9368
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.kunminx.linkage.LinkageRecyclerView.initLinkageSecondary(LinkageRecyclerView.java:168)
        at com.kunminx.linkage.LinkageRecyclerView.init(LinkageRecyclerView.java:299)
        at com.kunminx.linkagelistview.ui.ElemeSampleFragment.lambda$onViewCreated$0$ElemeSampleFragment(ElemeSampleFragment.java:80)
        at com.kunminx.linkagelistview.ui.-$$Lambda$ElemeSampleFragment$hd8Xu7jn5TF8Lkwto2wiclv4fms.onClick(lambda)
        at android.view.View.performClick(View.java:5657)
        at android.view.View$PerformClick.run(View.java:22453)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by KunMinX** [comment]
可以自己尝试解决，有好消息再来通知我

**Comment by huangliqiang** [comment]
> 你想解决这个问题的话，可以自行尝试调试和解决，有好消息可以再回来通知我
@KunMinX @HuangShun 
重复调用init报错的原因：

场景：
1. 当第一次和第二次调用init传入的list是同一个对象时会触发该BUG

原因：
1. init方法会先调用initRecyclerView
`this.initRecyclerView(primaryAdapterConfig, secondaryAdapterConfig);`

2. initRecyclerView 会 new LinkageSecondaryAdapter，这时候传入的mInitItems对象是非空的
`this.mSecondaryAdapter = new LinkageSecondaryAdapter(this.mInitItems, secondaryAdapterConfig);`

3. LinkageSecondaryAdapter创建后会持有mInitItems对象
`public LinkageSecondaryAdapter(List<BaseGroupedItem<T>> items, ILinkageSecondaryAdapterConfig<T> config) {`
`this.mItems = items;`

4.init方法执行mSecondaryAdapter.initData，会传入mInitItems
`this.mSecondaryAdapter.initData(this.mInitItems);`

5.这时候会把LinkageSecondaryAdapter持有的mInitItems对象执行clear，实际上这里已经把init方法传入的list数据清空了，导致这次绑定的list.size == 0
`public void initData(List<BaseGroupedItem<T>> list) {`
`this.mItems.clear();`

5.initLinkageSecondary方法执行到this.mInitItems.get(this.mFirstVisiblePosition))时，因为mInitItems是空，所以出现了IndexOutOfBoundsException错误
`initLinkageSecondary`
`if (((BaseGroupedItem)this.mInitItems.get(this.mFirstVisiblePosition)).isHeader) {`

解决方法：
每次init传入的list对象是新的对象，可以clone实现，不要传入上一次的list对象，实际上如果传入上一次的list对象也会导致被添加多个footerItem，也是会有异常的
